version: '3.8'

services:
  mysqldb-container:
    container_name: mysqldb-container
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: Db2023#
    ports:
      - '3306:3306'
    volumes:
      - ./build/mysql:/var/lib/mysql
      - ./resources/db.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - app-mysql-network

  backend-app-container:
    container_name: backend-app-container
    build:
      context: ./backend-app
    ports:
      - '80:8080'
    depends_on:
      - mysqldb-container
    networks:
      - app-mysql-network

networks:
  app-mysql-network: